spring:
#  config:
#    activate:
#      on-profile: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/toy?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234

  jpa:
#    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: create
    open-in-view: false
    show_sql: true

  redis:
    lettuce:
      pool:
      port: 6379
      host: 127.0.0.1
      password:
server:
  port: 8443
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore/sbip.p12
    key-store-password: p@ssw0rd
    key-alias: sbip



logging:
  level:
    org.hibernate.sql: debug #?? ????? ?? ?? ?? ?? ??? ? ?? ??!
    org.hibernate.type: trace #?? ??? ???.
